studentmarklist/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.home,name="home"),
    path("marklist",views.marklist,name="marklist"),
    
]

app1/models.py
from django.db import models

# Create your models here.
class Pedagogy(models.Model):
    subject = models.CharField(verbose_name="Pedagogy Subjects",max_length=30,null=False)
    class Meta:
        verbose_name = ("Pedagogy Subject")
    def __str__(self):
        return self.subject
    
    
class Deportment(models.Model):
    name = models.CharField(verbose_name="Deportment ",max_length=30,null=False)
    class Meta:
        verbose_name = ("Deportment List")
    def __str__(self):
        return self.name
    
class studentData(models.Model):
    name = models.CharField(verbose_name="Student Name ", max_length=50,null=False,unique=False)
    applicationNo =models.IntegerField(verbose_name="Application number",null=False,unique=True,primary_key=True)
    dob = models.DateField(("Date of Birth"), auto_now=False, auto_now_add=False,)
    deportment = models.ForeignKey("Deportment",on_delete=models.CASCADE,verbose_name=("Deportment Name"))
    pedagogy = models.ForeignKey("app1.Pedagogy", verbose_name=("pedagogy subject"), on_delete=models.CASCADE)
    
    s1T = models.IntegerField(verbose_name="Educational Psychology theary ",null=False )
    s2T = models.IntegerField(verbose_name="Contemporay India and Education theary ",null=False )
    s3T = models.IntegerField(verbose_name="Teaching and Learing theary ",null=False )
    s4T = models.IntegerField(verbose_name="Language across the Curriculum theary ",null=False )
    s5T = models.IntegerField(verbose_name="Pedagogy Subject theary ",null=False )
    
    s1A= models.IntegerField(verbose_name="Educational Psychology Assignment ",null=True,blank=True )
    s2A= models.IntegerField(verbose_name="Contemporay India and Education Assignment ",null=False )
    s3A= models.IntegerField(verbose_name="Teaching and Learing Assignment ",null=False )
    s4A= models.IntegerField(verbose_name="Language across the Curriculum Assignment ",null=False )
    s5A= models.IntegerField(verbose_name="Pedagogy Subject Assignment ",null=False )
    
    s1LS= models.IntegerField(verbose_name="Educational Psychology Late Submission Penalty Mark ",null=False ,default=0)
    s2LS= models.IntegerField(verbose_name="Contemporay India and Education Late Submission Penalty Mark ",null=False,default=0 )
    s3LS= models.IntegerField(verbose_name="Teaching and Learing Late Submission Penalty Mark ",null=False ,default=0)
    s4LS= models.IntegerField(verbose_name="Language across the Curriculum Late Submission Penalty Mark ",null=False,default=0 )
    s5LS= models.IntegerField(verbose_name="Pedagogy Subject Late Submission Penalty Mark ",null=False ,default=0)
    
    s1LS= models.IntegerField(verbose_name="Educational Psychology Late Submission Penalty Mark ",null=False ,default=0)
    s2LS= models.IntegerField(verbose_name="Contemporay India and Education Late Submission Penalty Mark ",null=False,default=0 )
    s3LS= models.IntegerField(verbose_name="Teaching and Learing Late Submission Penalty Mark ",null=False ,default=0)
    s4LS= models.IntegerField(verbose_name="Language across the Curriculum Late Submission Penalty Mark ",null=False,default=0 )
    s5LS= models.IntegerField(verbose_name="Pedagogy Subject Late Submission Penalty Mark ",null=False ,default=0)
    
    
    s1Total = models.IntegerField(verbose_name="Educational Psychology Total ",null=True,blank=True,default=0 )
    s2Total = models.IntegerField(verbose_name="Contemporay India and Education Total ",null=True,blank=True,default=0 )
    s3Total = models.IntegerField(verbose_name="Teaching and Learing Total ",null=True,blank=True ,default=0)
    s4Total = models.IntegerField(verbose_name="Language across the Curriculum Total ",null=True,blank=True ,default=0)
    s5Total = models.IntegerField(verbose_name="Pedagogy Subject Total ",null=True,blank=True,default=0 )
    
    total = models.IntegerField(verbose_name="Total Mark",null=True,blank=True,default=0)
    average = models.DecimalField(verbose_name="Average ",null=True,blank=True,max_digits=10,decimal_places=3,default=0)
    def save(self, *args, **kwargs):
       self.s1Total = self.s1A +self.s1LS +self.s1T
       self.s2Total = self.s2A +self.s2LS +self.s2T
       self.s3Total = self.s3A +self.s3LS +self.s3T
       self.s4Total = self.s4A +self.s4LS +self.s4T
       self.s5Total = self.s5A +self.s5LS +self.s5T
       
       
       self.total = self.s1Total+self.s2Total+self.s3Total+self.s4Total+self.s5Total
       
       self.average = self.total / 5
       
       super(studentData, self).save(*args, **kwargs) # Call the real save() method
    class Meta:
        verbose_name = ("Student Mark List")
        verbose_name_plural = ("Student Mark lists")

    def __str__(self):
        return self.name


app1/forms.py
from django import forms


class loginForm(forms.Form):
    studentId = forms.CharField( max_length=6, required=True)
    dob = forms.DateField(help_text="enter the Dob", required=True)

app1/views.py
from django.shortcuts import render,redirect
from .forms import loginForm
# Create your views here.
from .models import studentData,Deportment,Pedagogy
def home (request ):
    form = loginForm()
    return render(request,"home.html",{"form":form})

def marklist (request ):
    if request.method == "POST":
        form = loginForm(request.POST)
        if form.is_valid():
            # print(forms)
            stuId  = form.cleaned_data['studentId']
            dob  = form.cleaned_data['dob']
            print(stuId,dob)
            dat =  list(studentData.objects.filter(dob=dob, applicationNo=stuId).values())
            print(dat)
            if not dat:
                return redirect("home")
            print(dat[0]['deportment_id'])
            deportment = list(Deportment.objects.filter(id=dat[0]['deportment_id']).values("name"))
            print(deportment[0]['name'])
            pedagogy = list(Pedagogy.objects.filter(id=dat[0]['pedagogy_id']).values("subject"))
            print(pedagogy[0]['subject'])
            return render(request,"marklist.html",{"data":dat[0],"deportment":deportment[0]['name'],"pedagogy":pedagogy[0]['subject']})
        return redirect("home")
    return redirect("home") 


def excel(request):
    return render(request,'excel.html',{})

app1/templates/excel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="#" method="post">
        <input type="file" name="excel" id="excel">
        <input type="submit" value="submit">
    </form>
</body>
</html>

app1/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        

        .login-form {
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 20px;
            width: 300px;
        }

        input[type="text"],
        input[type="password"] {
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 8px;
            width: 100%;
            margin-bottom: 10px;
        }

        input[type="submit"] {
            background-color: rgb(0, 134, 176);
            color: white;
            border: none;
            border-radius: 5px;
            padding: 8px;
            width: 100%;
            cursor: pointer;
            margin-top: 10px;
        }
        .contain{
            display: flex;
            flex-direction: column;
            align-items : center;
            
        }
    </style>
</head>

<body>

    <!-- <form action="{% url 'marklist' %} " method="post" style="display: flex;align-items: center;justify-content: center;flex-direction: column;">  
        <label for="id_studentId">Studentid:</label>
        <input type="text" name="studentId" maxlength="6" required="" id="id_studentId">
        <label for="id_dob">Dob:</label>
        <input type="date" name="dob" required="" id="id_dob">
        {% csrf_token %}
        <input type="submit" value="submit">
    </form> -->
    <div class="contain">
        <img src="https://upload.wikimedia.org/wikipedia/en/9/99/The_Logo_of_St.Joseph_College_of_Education.png" alt="logo" width="100" height="100" style="margin-top: 10px;">
        <span class="text-capitalize text-center" ><h1 >St.Joseph College of Education</h1></span>
        <span class="text-capitalize text-center" > <h6>Kalakad Nanguneri Road,Kadamboduvalvu, Tirunelveli District, - 627108</h6></span>
        <span class="text-capitalize text-center"> <h2>1st - Intenal Exam Result- B.Ed. 1st Year Dec 2022</h2></span>

        <div style="margin-top: 50px;">
            <form class="login-form" action="{% url 'marklist' %} " method="post"> {% csrf_token %}
                <h2>Login</h2>
                <input type="text" placeholder="Roll No" name="studentId" maxlength="6" required=""
                    id="id_studentId">
                <label for="id_dob">Date Of Birth :</label>
                <input type="date" placeholder="Date Of Birth" name="dob" required="" id="id_dob">
                <input type="submit" value="Show result">
            </form>
    
        </div>
    </div>


</body>

</html>

</html>

app1/templates/marklist.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>detailss</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- <style>
        table {
        border-collapse: collapse;
        width: auto;
        border-color: black;
        }
        
        th, td {
        text-align: left;
        padding: 8px;
        }
        
        tr:nth-child(even){background-color: #f2f2f2}
        
        th {
        background-color: #4CAF50;
        color: white;
        }
        </style> -->

</head>

<body class="container-sm">

    <div class="m-4 p-2">

        <div><b>Name : </b><span>{{data.name}}</span></div>
        <div><b>Department : </b><span>{{deportment}}</span></div>
    </div>
      
    
    <table id="myTableId" class="table border border-5 m-4 p-4">
        <thead class="bg-tablehead" style="background-color: rgb(127, 211, 223);">

            <tr>
                <th>Subject</th>
                <th>Theory Exam (35)</th>
                <th>Assignment (15)</th>
                <th>Late Submission Penalty Mark (50)</th>
                <th> Total Marks (50)</th>
            </tr>
        </thead>
        <tr>
            <th>Educational Psychology</th>
            <td>{{data.s1T}}</td>
            <td>{{data.s1A}}</td>
            <td>{{data.s1LS}}</td>
            <td>{{data.s1Total}}</td>
        </tr>
        <tr>
            <th>Contemporay India and Education</th>
            <td>{{data.s2T}}</td>
            <td>{{data.s2A}}</td>
            <td>{{data.s2LS}}</td>
            <td>{{data.s2Total}}</td>
        </tr>
        <tr>
            <th>Teaching and Learing</th>
            <td>{{data.s3T}}</td>
            <td>{{data.s3A}}</td>
            <td>{{data.s3LS}}</td>
            <td>{{data.s3Total}}</td>
        </tr>
        <tr>
            <th>Language across the Curriculum</th>
            <td>{{data.s4T}}</td>
            <td>{{data.s4A}}</td>
            <td>{{data.s4LS}}</td>
            <td>{{data.s4Total}}</td>
        </tr>
        <tr>
            <th>{{pedagogy}}</th>
            <td>{{data.s5T}}</td>
            <td>{{data.s5A}}</td>
            <td>{{data.s5LS}}</td>
            <td>{{data.s5Total}}</td>
        </tr>
        <tr>
            <th>Total</th>
            <td></td>
            <td></td>
            <td></td>
            <td><b>{{data.total}}</b> </td>
        </tr>
        <tr>
            <th>Percentage</th>
            <td></td>
            <td></td>
            <td></td>
            <td> <b>{{data.average}}</b></td>
        </tr>
    </table>

    {{dob}}
</body>

</html>